from django.urls import path, include
from rest_framework.routers import DefaultRouter
from inventory import views

# Initialize the DefaultRouter
router = DefaultRouter()

# Register your viewsets with the router
router.register(r'bloodstocks', views.BloodStockViewSet, basename='bloodstock')
router.register(r'attendants', views.AttendantViewSet)
router.register(r'donors', views.DonorViewSet)

# Include the router URLs
urlpatterns = [
    path('', include(router.urls)),  # This will include all the routes generated by the router
]